apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: &app httpbin
  name: *app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:     
      containers:
      - image: docker.io/citizenstig/httpbin
        name: *app
        ports:
        - containerPort: &port 8080
        livenessProbe:
          httpGet:
            path: /get
            port: *port
          timeoutSeconds: 1
