apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  namespace: httpbin
  name: zone-ingress
spec:
  template:
    spec:
      backend:
        serviceName: zone-mcs
        servicePort: 8000
